# Video
vo=gpu
profile=gpu-hq
hwdec=auto
scale=ewa_lanczossharp
cscale=ewa_lanczossharp

# Audio
audio-file-auto=fuzzy
audio-pitch-correction=yes
volume=70
volume-max=150

# Subtitles
sub-auto=fuzzy
sub-file-paths=ass:srt:sub:subs:subtitles
sub-font="Sans"
sub-font-size=48
sub-color="#FFFFFFFF"
sub-border-color="#FF000000"
sub-border-size=2
sub-shadow-offset=1
sub-shadow-color="#33000000"

# UI
osd-font="Sans"
osd-font-size=32
osd-color="#FFFFFFFF"
osd-border-color="#FF000000"

# Screenshots
screenshot-format=png
screenshot-png-compression=8
screenshot-template='~/Pictures/Screenshots/mpv-%F-%P'
screenshot-directory=~/Pictures/Screenshots

# Misc
save-position-on-quit
keep-open=yes
